{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0a44c4ea-4cf3-424d-8976-e5791a26fc3a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\rijaf\\anaconda3\\Lib\\site-packages\\pygame\\pkgdata.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.\n",
      "  from pkg_resources import resource_stream, resource_exists\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pygame 2.6.1 (SDL 2.28.4, Python 3.13.9)\n",
      "Hello from the pygame community. https://www.pygame.org/contribute.html\n"
     ]
    }
   ],
   "source": [
    "import pygame\n",
    "import math\n",
    "import random\n",
    "import time\n",
    "from queue import PriorityQueue\n",
    "\n",
    "# --- 1. SETTINGS & COLORS ---\n",
    "WIDTH = 800\n",
    "SIDEBAR_WIDTH = 250\n",
    "ROWS = 40 \n",
    "GAP = WIDTH // ROWS\n",
    "\n",
    "# Requirement: Mandatory Visual Elements\n",
    "WHITE = (255, 255, 255) # Empty\n",
    "BLACK = (0, 0, 0)       # Wall\n",
    "GREY = (128, 128, 128)  # Grid\n",
    "ORANGE = (255, 165, 0)  # Start\n",
    "PURPLE = (128, 0, 128)  # Goal\n",
    "YELLOW = (255, 255, 0)  # Frontier (Priority Queue)\n",
    "RED = (255, 0, 0)       # Visited\n",
    "GREEN = (0, 255, 0)     # Final Path\n",
    "CYAN = (0, 255, 255)    # Agent\n",
    "\n",
    "class Node:\n",
    "    def __init__(self, row, col, width, total_rows):\n",
    "        self.row, self.col = row, col\n",
    "        self.x, self.y = row * width, col * width\n",
    "        self.color = WHITE\n",
    "        self.neighbors = []\n",
    "        self.width, self.total_rows = width, total_rows\n",
    "\n",
    "    def get_pos(self): return self.row, self.col\n",
    "    def is_wall(self): return self.color == BLACK\n",
    "    def reset(self): self.color = WHITE\n",
    "    def make_start(self): self.color = ORANGE\n",
    "    def make_closed(self): self.color = RED\n",
    "    def make_open(self): self.color = YELLOW\n",
    "    def make_wall(self): self.color = BLACK\n",
    "    def make_goal(self): self.color = PURPLE\n",
    "    def make_path(self): self.color = GREEN\n",
    "    def make_agent(self): self.color = CYAN\n",
    "\n",
    "    def draw(self, win):\n",
    "        pygame.draw.rect(win, self.color, (self.x, self.y, self.width, self.width))\n",
    "\n",
    "    def update_neighbors(self, grid):\n",
    "        self.neighbors = []\n",
    "        dirs = [(1, 0), (-1, 0), (0, 1), (0, -1)]\n",
    "        for dr, dc in dirs:\n",
    "            r, c = self.row + dr, self.col + dc\n",
    "            if 0 <= r < self.total_rows and 0 <= c < self.total_rows:\n",
    "                if not grid[r][c].is_wall():\n",
    "                    self.neighbors.append(grid[r][c])\n",
    "\n",
    "# --- 2. SEARCH STRATEGIES (FORMULAS) ---\n",
    "# Manhattan: |x1 - x2| + |y1 - y2|\n",
    "def h_manhattan(p1, p2):\n",
    "    return abs(p1[0] - p2[0]) + abs(p1[1] - p2[1])\n",
    "\n",
    "# Euclidean: sqrt((x1 - x2)^2 + (y1 - y2)^2)\n",
    "def h_euclidean(p1, p2):\n",
    "    return math.sqrt((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)\n",
    "\n",
    "def reconstruct_path(came_from, current, draw):\n",
    "    path = []\n",
    "    while current in came_from:\n",
    "        path.append(current)\n",
    "        current = came_from[current]\n",
    "        if current.color not in [ORANGE, PURPLE]: current.make_path()\n",
    "        draw()\n",
    "    return path[::-1]\n",
    "\n",
    "def search(draw, grid, start, goal, algo_type=\"A*\", heuristic=\"Manhattan\"):\n",
    "    count = 0\n",
    "    open_set = PriorityQueue()\n",
    "    open_set.put((0, count, start))\n",
    "    came_from = {}\n",
    "    g_score = {node: float(\"inf\") for row in grid for node in row}\n",
    "    g_score[start] = 0\n",
    "    \n",
    "    h_func = h_manhattan if heuristic == \"Manhattan\" else h_euclidean\n",
    "    nodes_visited = 0\n",
    "\n",
    "    while not open_set.empty():\n",
    "        for event in pygame.event.get():\n",
    "            if event.type == pygame.QUIT: return None, 0\n",
    "            \n",
    "        current = open_set.get()[2]\n",
    "        nodes_visited += 1\n",
    "        if current == goal:\n",
    "            return reconstruct_path(came_from, goal, draw), nodes_visited\n",
    "\n",
    "        for neighbor in current.neighbors:\n",
    "            temp_g = g_score[current] + 1\n",
    "            if temp_g < g_score[neighbor]:\n",
    "                came_from[neighbor] = current\n",
    "                g_score[neighbor] = temp_g\n",
    "                # A* formula: f(n) = g(n) + h(n)\n",
    "                # GBFS formula: f(n) = h(n)\n",
    "                f = temp_g + h_func(neighbor.get_pos(), goal.get_pos()) if algo_type == \"A*\" else h_func(neighbor.get_pos(), goal.get_pos())\n",
    "                count += 1\n",
    "                open_set.put((f, count, neighbor))\n",
    "                if neighbor != goal: neighbor.make_open()\n",
    "        draw()\n",
    "        if current != start: current.make_closed()\n",
    "    return None, nodes_visited\n",
    "\n",
    "# --- 3. MAIN LOOP & DYNAMIC RE-PLANNING ---\n",
    "def make_grid(rows, width):\n",
    "    return [[Node(i, j, width // rows, rows) for j in range(rows)] for i in range(rows)]\n",
    "\n",
    "def draw_window(win, grid, rows, width, metrics):\n",
    "    win.fill(WHITE)\n",
    "    for row in grid:\n",
    "        for node in row: node.draw(win)\n",
    "    \n",
    "    gap = width // rows\n",
    "    for i in range(rows):\n",
    "        pygame.draw.line(win, GREY, (0, i * gap), (width, i * gap))\n",
    "        pygame.draw.line(win, GREY, (i * gap, 0), (i * gap, width))\n",
    "    \n",
    "    font = pygame.font.SysFont('Arial', 18)\n",
    "    y = 20\n",
    "    for k, v in metrics.items():\n",
    "        win.blit(font.render(f\"{k}: {v}\", True, BLACK), (width + 15, y))\n",
    "        y += 35\n",
    "    pygame.display.update()\n",
    "\n",
    "def main():\n",
    "    pygame.init()\n",
    "    win = pygame.display.set_mode((WIDTH + SIDEBAR_WIDTH, WIDTH))\n",
    "    pygame.display.set_caption(\"Dynamic Pathfinding Agent\")\n",
    "    \n",
    "    grid = make_grid(ROWS, WIDTH)\n",
    "    start = goal = None\n",
    "    metrics = {\"Algo\": \"A*\", \"Heuristic\": \"Manhattan\", \"Visited\": 0, \"Cost\": 0, \"Time\": \"0ms\", \"Mode\": \"Static\"}\n",
    "    \n",
    "    run = True\n",
    "    while run:\n",
    "        draw_window(win, grid, ROWS, WIDTH, metrics)\n",
    "        for event in pygame.event.get():\n",
    "            if event.type == pygame.QUIT: run = False\n",
    "            \n",
    "            if pygame.mouse.get_pressed()[0]: # Left Click: Start/Goal/Walls\n",
    "                pos = pygame.mouse.get_pos()\n",
    "                if pos[0] < WIDTH:\n",
    "                    node = grid[pos[0] // GAP][pos[1] // GAP]\n",
    "                    if not start: start = node; start.make_start()\n",
    "                    elif not goal and node != start: goal = node; goal.make_goal()\n",
    "                    elif node != start and node != goal: node.make_wall()\n",
    "            \n",
    "            if event.type == pygame.KEYDOWN:\n",
    "                if event.key == pygame.K_a: metrics[\"Algo\"] = \"A*\"\n",
    "                if event.key == pygame.K_g: metrics[\"Algo\"] = \"GBFS\"\n",
    "                if event.key == pygame.K_m: metrics[\"Heuristic\"] = \"Manhattan\"\n",
    "                if event.key == pygame.K_e: metrics[\"Heuristic\"] = \"Euclidean\"\n",
    "                if event.key == pygame.K_d: metrics[\"Mode\"] = \"Dynamic\" if metrics[\"Mode\"] == \"Static\" else \"Static\"\n",
    "                if event.key == pygame.K_r: # Randomize (30% density)\n",
    "                    for row in grid:\n",
    "                        for n in row:\n",
    "                            if n not in [start, goal]:\n",
    "                                n.reset()\n",
    "                                if random.random() < 0.3: n.make_wall()\n",
    "\n",
    "                if event.key == pygame.K_SPACE and start and goal:\n",
    "                    for row in grid:\n",
    "                        for n in row: n.update_neighbors(grid)\n",
    "                    \n",
    "                    t1 = time.time()\n",
    "                    path, visited = search(lambda: draw_window(win, grid, ROWS, WIDTH, metrics), grid, start, goal, metrics[\"Algo\"], metrics[\"Heuristic\"])\n",
    "                    t2 = time.time()\n",
    "                    \n",
    "                    if path:\n",
    "                        metrics[\"Visited\"], metrics[\"Cost\"], metrics[\"Time\"] = visited, len(path), f\"{int((t2-t1)*1000)}ms\"\n",
    "                        # Dynamic Mode Logic\n",
    "                        if metrics[\"Mode\"] == \"Dynamic\":\n",
    "                            curr_idx = 0\n",
    "                            while curr_idx < len(path):\n",
    "                                step_node = path[curr_idx]\n",
    "                                if random.random() < 0.15: # Random spawn chance\n",
    "                                    obs_node = grid[random.randint(0, ROWS-1)][random.randint(0, ROWS-1)]\n",
    "                                    if obs_node not in [start, goal, step_node]: \n",
    "                                        obs_node.make_wall()\n",
    "                                        if obs_node in path[curr_idx:]: # Re-plan if blocked\n",
    "                                            for row in grid:\n",
    "                                                for n in row: n.update_neighbors(grid)\n",
    "                                            path, _ = search(lambda: draw_window(win, grid, ROWS, WIDTH, metrics), grid, step_node, goal, metrics[\"Algo\"], metrics[\"Heuristic\"])\n",
    "                                            if not path: break\n",
    "                                            curr_idx = 0 \n",
    "                                step_node.make_agent()\n",
    "                                draw_window(win, grid, ROWS, WIDTH, metrics)\n",
    "                                time.sleep(0.05)\n",
    "                                curr_idx += 1\n",
    "                    else: metrics[\"Cost\"] = \"Blocked\"\n",
    "\n",
    "    pygame.quit()\n",
    "\n",
    "main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6ad01bb3-9d85-4586-9deb-4fdb4ca747a1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
